version: "3.8"

services:
  app1:
    build: .
    container_name: express_1
    environment:
      - INSTANCE_ID=1

  app2:
    build: .
    container_name: express_2
    environment:
      - INSTANCE_ID=2

  app3:
    build: .
    container_name: express_3
    environment:
      - INSTANCE_ID=3

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
